version: '3'


services:
  app:
    build:
      dockerfile: dockerfiles/Dockerfile.prod
      context: .
    image: neom_backend:1.0
    container_name: neom_backend
    command: python app.py
    volumes:
      - ./.env:/app/.env
    ports:
      - "8080:5000"


  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
